server:
  port: 8080

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:19999/rsa/publicKey #配置RSA的公钥访问地址
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth_route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
#            - RewritePath=/auth/(?<segment>.*),/$\{segment}
            - StripPrefix=1 # 跟上面方式效果一样

        - id: system_route
          uri: lb://system-service
          predicates:
            - Path=/sys/**,/gen/**

        - id: third_route
          uri: lb://third-service
          predicates:
            - Path=/third/**
          filters:
            - StripPrefix=1

        - id: info_route
          uri: lb://info-service
          predicates:
            - Path=/info/**
          filters:
            - StripPrefix=1

        - id: purchase_route
          uri: lb://purchase-service
          predicates:
            - Path=/purchase/**

        - id: warehouse_route
          uri: lb://warehouse-service
          predicates:
            - Path=/warehouse/**

        - id: sale_route
          uri: lb://sale-service
          predicates:
            - Path=/sale/**
  data:
    redis:
      host: 192.168.0.250
      port: 6379
      password: 123456