spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 127.0.0.1:8848
      config:
        namespace:
  config:
    import:
      - nacos:vector-common.yaml?refresh=true
      - nacos:${spring.application.name}.yaml?refresh=true

knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      # 开启
      enabled: true
        # 指定版本号(swagger2|openapi3)
      version: openapi3
        # 需要排除的微服务(eg:网关服务)
      excluded-services:
          - ${spring.application.name}