server:
  port: 10000

spring:
  application:
    name: system-service
  profiles:
    active: dev
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:application-${spring.profiles.active}.yaml
      - nacos:common-redis-${spring.profiles.active}.yaml
      - nacos:${spring.application.name}-${spring.profiles.active}.yaml?refresh=true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  pattern:
    console: "%d [%thread] %-5level %logger - %msg%n"
  level:
    com.vector: debug
