spring:
  rabbitmq:
    host: 192.168.0.250
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1 # 每个使用者可以处理的未确认消息的最大数量。
        retry:
          enabled: true # 开启消费失败重试
          max-attempts: 3 # 最大重试次数
          initial-interval: 1000ms # 第一次和第二次尝试传递消息之间的持续时间
          multiplier: 1 # 应用于上一次重试间隔的乘数。
          max-interval: 10000ms # 两次尝试之间的最长持续时间
          stateless: true # 重试是无状态的还是有状态的。有事务选false