mysql:
  host: localhost
  port: 3306
  username: root
  password: root

redis:
  host: 192.168.0.250
  port: 6379
  password: 123456

rabbitmq:
  host: 192.168.0.250
  port: 5672
  username: guest
  password: guest

# 验签公钥地址
spring:
  security:
    oauth2:
      authorizationserver:
        token-uri: ${gateway.endpoint}/auth-api/oauth2/token
      resourceserver:
        jwt: 
          jwk-set-uri: ${gateway.endpoint}/auth-api/oauth2/jwks

# 网关地址
gateway:
  endpoint: http://localhost:8080

# 短信模版代码
sms:
  aliyun:
    template-code:
      login: SMS_12345678