spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 127.0.0.1:8848
      config:
        namespace:
  config:
    import:
      - nacos:vector-common.yaml?refresh=true
      - nacos:${spring.application.name}.yaml?refresh=true

  security:
    oauth2:
      authorizationserver:
        token-uri: ${gateway.endpoint}/youlai-auth/oauth2/token
      resourceserver:
        jwt:
          jwk-set-uri: ${gateway.endpoint}/youlai-auth/oauth2/jwks
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.vector.system.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
